// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZISpv7W_E8z0z5go9FMl7TSlbkbVZU8',
    appId: '1:450460249427:web:64439468892e8aace885a6',
    messagingSenderId: '450460249427',
    projectId: 'lag-clothing-e4567',
    authDomain: 'lag-clothing-e4567.firebaseapp.com',
    storageBucket: 'lag-clothing-e4567.firebasestorage.app',
    measurementId: 'G-V2L0M91N68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJJROxre-0QaitIckozvSvB3bj5-hjHM8',
    appId: '1:450460249427:android:ed8670ece5dc67efe885a6',
    messagingSenderId: '450460249427',
    projectId: 'lag-clothing-e4567',
    storageBucket: 'lag-clothing-e4567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLIPg-PSC_8wpOsYWCJ9PuyxlQakchL4',
    appId: '1:450460249427:ios:4590e811c701d1ebe885a6',
    messagingSenderId: '450460249427',
    projectId: 'lag-clothing-e4567',
    storageBucket: 'lag-clothing-e4567.firebasestorage.app',
    iosBundleId: 'com.example.lagClothing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCLIPg-PSC_8wpOsYWCJ9PuyxlQakchL4',
    appId: '1:450460249427:ios:4590e811c701d1ebe885a6',
    messagingSenderId: '450460249427',
    projectId: 'lag-clothing-e4567',
    storageBucket: 'lag-clothing-e4567.firebasestorage.app',
    iosBundleId: 'com.example.lagClothing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRZISpv7W_E8z0z5go9FMl7TSlbkbVZU8',
    appId: '1:450460249427:web:e6fcd041e3336c32e885a6',
    messagingSenderId: '450460249427',
    projectId: 'lag-clothing-e4567',
    authDomain: 'lag-clothing-e4567.firebaseapp.com',
    storageBucket: 'lag-clothing-e4567.firebasestorage.app',
    measurementId: 'G-QH0KCCGW5B',
  );
}
